name: amoboard_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  path_provider: ^2.0.14
  path: ^1.8.3
  file_picker: ^10.3.7
  flutter_colorpicker: ^1.1.0
  just_audio: ^0.9.38
  image_cropper: ^11.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Amogus_Logo_Apki.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/1024.png"

flutter:
  uses-material-design: true

  assets:
    # Ikony UI
    - assets/Megafon_Na_Czerwonym.png
    - assets/xd.png
    - assets/earrape_icon.png
    - assets/Amogus_Logo_Apki.png
    - assets/Amongus_Logo_W_Apce.png
    - assets/1024.png